project:
  type: website
  output-dir: docs

website:
  title: "Michael Fehl"
  site-url: "https://mtfehl.github.io/econ_portfolio/"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: projects.qmd
      - text: "Classes"
        menu:
          - text: "Home"
            href: classes.qmd
          - text: "Geospatial"
            href: https://mtfehl.github.io/geospatial/
          - text: "Econometrics: Time Series"
            href: https://mtfehl.github.io/finc_metrics/
          - text: "Networks: Concepts & Algorithms"
            href: https://mtfehl.github.io/networks/
          - text: "Econometrics: Panel Data"
            href: https://mtfehl.github.io/econometrics2/
      - text: "About Me"
        href: about.qmd
      - text: "CV"          
        href: file/Fehl_Michael.pdf
    right:
      - icon: github
        href: https://github.com/mtfehl
        #aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/michael-t-fehl
        #aria-label: LinkedIn
      - icon: envelope
        href: "mailto:michaelthomasfehl@gmail.com"
        #aria-label: Email

format:
  html:
    theme: cosmo    
    css: styles.css
    toc: true